FROM php:8.2-apache

# Set the working directory inside the container
WORKDIR /var/www/html

# Copy the project files from the frontend folder
COPY frontend/ ./

# Expose port 80 to the host machine
EXPOSE 80
